-- SUPABASE SCHEMA
create table if not exists players (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  rank text default '',
  games int not null default 0,
  wins int not null default 0,
  shells int not null default 0,
  used_shells int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists shell_events (
  id bigint generated by default as identity primary key,
  player_id uuid references players(id) on delete cascade,
  type text not null,
  target_player_id uuid references players(id) on delete set null,
  note text default '',
  created_at timestamptz not null default now()
);
create table if not exists game_results (
  id bigint generated by default as identity primary key,
  player_id uuid references players(id) on delete cascade,
  win boolean not null,
  played_at timestamptz not null default now()
);
